services:
  backend:
    build: ./backend
    image: ctf-platform-backend:ci
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
      DB_USER: postgres.hpbmeowxtqmbiyrbmgjm
      DB_PASSWORD: UVcq4Ji4Q6LoLOAg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ctf-platform/"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    image: ctf-platform-frontend:ci
    ports:
      - "80:80"
    depends_on:
      - backend