version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
      - DB_USER=postgres.hpbmeowxtqmbiyrbmgjm
      - DB_PASSWORD=UVcq4Ji4Q6LoLOAg

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
