# ===================================
# Configuration Base de Données
# ===================================

# URL de connexion PostgreSQL
db.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require

# Identifiants
db.username=postgres.hpbmeowxtqmbiyrbmgjm
db.password=UVcq4Ji4Q6LoLOAg
db.driver=org.postgresql.Driver

# ===================================
# Configuration HikariCP (Pool)
# ===================================

# Nombre maximum de connexions dans le pool
db.pool.maximumPoolSize=10

# Nombre minimum de connexions maintenues
db.pool.minimumIdle=2

# Temps max d'attente pour obtenir une connexion (ms) = 30s
db.pool.connectionTimeout=30000

# Temps max qu'une connexion peut rester inactive (ms) = 10min
db.pool.idleTimeout=600000

# Durée de vie maximale d'une connexion (ms) = 30min
db.pool.maxLifetime=1800000

